language: node_js

# node_js: # not needed - `.nvmrc` at root-level

cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
 - yarn global add greenkeeper-lockfile@1

install:
  - yarn install --frozen-lockfile --silent

before_script:
 - greenkeeper-lockfile-update

after_script:
 - greenkeeper-lockfile-upload

script:
  - yarn lint
  - yarn test:ci
  - yarn build

deploy:
  - provider: script
    script: echo 'No build on feature branches. Now deploys static exports automatically.'
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: yarn add now && now --local-config "./now.master.json" --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
