language: node_js

# node_js: # not needed - `.nvmrc` at root-level

cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - yarn test
  - yarn build

before_deploy: yarn add now # Install Now CLI

deploy:
  - provider: script # Run a custom deployment script which we will define below
    script: now --token $NOW_TOKEN --public
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: yarn start
    skip_cleanup: true
    on:
      master: true
