version: 2.1

orbs:
  cypress: cypress-io/cypress@1.16.1

executors:
  default:
    docker:
      - image: cypress/base:12.16.1 # keep in sync with .nvmrc and any other executors
    environment:
      CC_TEST_REPORTER_ID: 0f2bc6ef737019bfc8eda369cd06b66c54606b144b4d81cec010fb494d2559af

parameters:
  workspace_root:
    type: string
    default: '~/'
  cache_key:
    type: string
    default: 'dependencies-2-{{ checksum "yarn.lock" }}'

aliases:
  - &restore_cache
    keys:
      - << pipeline.parameters.cache_key >>

jobs:
  install_dependencies:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: << pipeline.parameters.workspace_root >>
      - restore_cache: *restore_cache
      - run:
          name: Install dependencies
          command: yarn install --non-interactive --frozen-lockfile --production=false --cache-folder << pipeline.parameters.workspace_root >>.cache/yarn
      - save_cache:
          key: << pipeline.parameters.cache_key >>
          paths:
            - node_modules
            - << pipeline.parameters.workspace_root >>.cache
            - << pipeline.parameters.workspace_root >>.cache/yarn
            - << pipeline.parameters.workspace_root >>.cache/Cypress

  unit-tests:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: << pipeline.parameters.workspace_root >>
      - restore_cache: *restore_cache
      - run:
          name: Run tests
          command: |
            yarn test:ci --silent=false
      - persist_to_workspace:
          root: << pipeline.parameters.workspace_root >>
          paths:
            - project/jest-coverage


  lint:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: << pipeline.parameters.workspace_root >>
      - restore_cache: *restore_cache
      - run:
          name: Lint
          command: |
            yarn lint:ci

workflows:
  default:
    jobs:
      - install_dependencies

      # - unit-tests:
      #     requires:
      #       - install_dependencies

      # - lint:
      #     requires:
      #       - install_dependencies

      # Only created to ensure maximum possible simultaneous work
      - cypress/install:
          executor: default
          requires:
            - install_dependencies
          name: cypress/install
          yarn: true
          cache-key: << pipeline.parameters.cache_key >>

      - cypress/run:
          executor: default
          requires:
            - unit-tests
            - cypress/install
          name: cypress/run
          record: true # record results on Cypress Dashboard
          yarn: true # use yarn instead of npm
          cache-key: << pipeline.parameters.cache_key >>
          parallel: true # split all specs across machines
          parallelism: 3 # use 3 CircleCI machines to finish quickly
          group: 'all tests' # name this group "all tests" on the dashboard
          start: 'yarn dev' # start server before running tests
          wait-on: http://localhost:3000 # wait until server is ready
          post-steps:
            - run:
                name: Initialize CodeClimate
                command: |
                  curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc_test_reporter
                  chmod +x ./cc_test_reporter
            - run:
                name: Debug
                command: |
                  ls -al
                  ls -al coverage
                  ls -al cypress-coverage
                  ls -al jest-coverage
            - run:
                name: Move reports to one folder
                run: |
                  cp cypress-coverage/coverage-final.json reports/from-cypress.json && cp jest-coverage/coverage-final.json reports/from-jest.json
            - run:
                name: Merging reports into one file
                run: |
                  yarn nyc merge reports
                  mv coverage.json .nyc_output/out.json
            - run:
                name: Creating lcov report from final
                run: |
                  yarn nyc report --reporter lcov --report-dir coverage
            - run:
                name: Formatting CodeClimate Test Report
                run: |
                  ./cc_test_reporter format-coverage -t lcov -o coverage/codeclimate.json coverage/lcov.info
            - run:
                name: Uploading CodeClimate Test Report
                run: |
                  ./cc_test_reporter upload-coverage --debug --input coverage/codeclimate.json
